# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

formats:
  - pdf

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - python build_scripts/update_docs.py --clean
