name: Upload Python Package to PyPI

on:
  push:
    tags:
    - "v*"
  workflow_dispatch:
    inputs:
      reason:
        description: Why did you trigger the pipeline?
        required: False
        default: Check if it runs again due to external changes

env:
  PY_COLORS: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fail if not on 'master' branch
        if: github.ref != 'refs/heads/master'
        run: exit -1
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - name: Install Dev Requirements
        run: pip install -r requirements-dev.txt
      - name: Build and publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: tox -e publish-release-package
