name: Merge develop, run tests and build docu

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  GITHUB_BOT_USERNAME: github-actions[bot]
  GITHUB_BOT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge develop into current branch
        run: |
          git fetch origin develop:develop --update-head-ok
          git merge develop
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: 'pip'
      - name: Install Dev Requirements
        run: pip install -r requirements-dev.txt
      - name: Run Tox
        run: tox
      - name: Test Torch Modules
        run: tox -e torch
      - name: Test Notebooks
        run: tox -e test-notebooks
        continue-on-error: true
      - name: Install Pandoc
        run: sudo apt-get install --no-install-recommends --yes pandoc
      - name: Build Docs
        run: tox -e docs
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/develop' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          user_name: ${{ env.GITHUB_BOT_USERNAME }}
          user_email: ${{ env.GITHUB_BOT_EMAIL }}
      - name: Build and publish to TestPyPI
        # if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          git config user.name "${{ env.GITHUB_BOT_USERNAME }}"
          git config user.email "${{ env.GITHUB_BOT_EMAIL }}"
          tox -e bump-dev-version-and-create-tag
          # tox -e publish-test-package
          git push --atomic origin --tags
